const KEY='zhixue_pages_v1';
let state=load(),filter='all',activeTool='教学行动';
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{questions:[],tasks:[]}}catch{return{questions:[],tasks:[]}}}
function save(){localStorage.setItem(KEY,JSON.stringify(state));render()}
function uid(){return Date.now().toString(36)+Math.random().toString(36).slice(2,6)}
function esc(s=''){return s.replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function toast(t){const e=document.querySelector('.toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.tt);window.tt=setTimeout(()=>e.classList.remove('show'),2200)}
function empty(a,b){return `<div class="empty"><b>${a}</b>${b}</div>`}
function qhtml(q,teacher=false){return `<article class="item"><div class="item-top"><div class="item-text">${esc(q.text)}</div><span class="badge ${q.status==='done'?'done':''}">${q.status==='done'?'已答复':'等待回复'}</span></div><div class="meta">${new Date(q.created).toLocaleString('zh-CN')}</div>${q.answer?`<div class="answer"><b>教师回复</b><br>${esc(q.answer)}</div>`:''}${teacher?`<div class="item-actions"><button class="iconbtn" onclick="toggleReply('${q.id}')">${q.answer?'修改回复':'回复'}</button><button class="iconbtn" onclick="removeQuestion('${q.id}')">删除</button></div><div class="reply" id="reply-${q.id}"><textarea placeholder="写下清晰、具体的回复">${esc(q.answer)}</textarea><button class="btn primary sm" onclick="saveReply('${q.id}')">保存回复</button></div>`:`<div class="item-actions"><button class="iconbtn" onclick="removeQuestion('${q.id}')">删除记录</button>${q.answer?`<button class="iconbtn" onclick="toast('已记录你的反馈')">有帮助</button>`:''}</div>`}</article>`}
function thtml(t){return `<article class="item task ${t.done?'done':''}"><input type="checkbox" ${t.done?'checked':''} onchange="toggleTask('${t.id}')"><div class="grow"><div class="item-text">${esc(t.text)}</div><div class="meta">${t.date||'未设置日期'}</div></div><button class="iconbtn" onclick="removeTask('${t.id}')">删除</button></article>`}
function openView(v){document.querySelectorAll('.view').forEach(x=>x.classList.toggle('on',x.id===v));document.querySelectorAll('.menu').forEach(x=>x.classList.toggle('on',x.dataset.view===v));const m={home:['学习首页','查看课程、任务和最近问题。'],courses:['我的课程','继续学习并掌握课程进度。'],questions:['问题记录','持续跟踪每个问题是否真正解决。'],planner:['复习计划','把学习目标拆成具体任务。'],teacherHome:['教学首页','及时掌握问题处理与学习任务情况。'],inbox:['问题收件箱','回应学生尚未解决的困惑。'],tools:['教学工具','把真实学情转化为下一步教学行动。'],data:['数据管理','导出、导入或清理当前设备数据。']}[v];if(m){document.querySelector('.page-title').textContent=m[0];document.querySelector('.page-desc').textContent=m[1]}render()}
document.querySelectorAll('.menu').forEach(x=>x.onclick=()=>openView(x.dataset.view));
function addQuestion(){const e=document.querySelector('#questionInput');if(!e||!e.value.trim()){toast('请先写下问题');return}state.questions.unshift({id:uid(),text:e.value.trim(),status:'pending',answer:'',created:new Date().toISOString()});e.value='';save();toast('问题已进入教师收件箱')}
function addTask(){const e=document.querySelector('#taskInput'),d=document.querySelector('#taskDate');if(!e||!e.value.trim()){toast('请填写具体任务');return}state.tasks.unshift({id:uid(),text:e.value.trim(),date:d?.value||'',done:false,created:new Date().toISOString()});e.value='';save();toast('任务已添加')}
window.toggleTask=id=>{const t=state.tasks.find(x=>x.id===id);if(t)t.done=!t.done;save()};window.removeTask=id=>{state.tasks=state.tasks.filter(x=>x.id!==id);save()};window.removeQuestion=id=>{state.questions=state.questions.filter(x=>x.id!==id);save()};window.toggleReply=id=>document.querySelector('#reply-'+id)?.classList.toggle('on');window.saveReply=id=>{const q=state.questions.find(x=>x.id===id),v=document.querySelector(`#reply-${id} textarea`).value.trim();if(!v){toast('请填写回复');return}q.answer=v;q.status='done';save();toast('回复已同步给学生')};window.toast=toast;
function trend(qs){const box=document.querySelector('#trend');if(!box)return;const days=Array.from({length:7},(_,i)=>{const d=new Date();d.setDate(d.getDate()-(6-i));return d}),c=days.map(d=>qs.filter(q=>new Date(q.created).toDateString()===d.toDateString()).length),max=Math.max(1,...c);box.innerHTML=days.map((d,i)=>`<div class="barw"><div class="bar" style="--h:${Math.max(4,c[i]/max*100)}%"></div>${'日一二三四五六'[d.getDay()]}</div>`).join('')}
function render(){const qs=state.questions||[],ts=state.tasks||[],pending=qs.filter(q=>q.status==='pending').length,done=ts.filter(t=>t.done).length,rate=ts.length?Math.round(done/ts.length*100):0;
 const set=(s,v)=>{const e=document.querySelector(s);if(e)e.innerHTML=v},txt=(s,v)=>{const e=document.querySelector(s);if(e)e.textContent=v};
 set('#recentQuestions',qs.length?qs.slice(0,3).map(q=>qhtml(q)).join(''):empty('还没有问题','遇到困惑时，及时记录下来。'));
 set('#questionList',qs.length?qs.map(q=>qhtml(q)).join(''):empty('还没有问题记录','从学习首页提交第一个问题。'));
 set('#taskPreview',ts.filter(t=>!t.done).length?ts.filter(t=>!t.done).slice(0,3).map(thtml).join(''):empty('暂无待办','添加一项今天能完成的任务。'));
 set('#taskList',ts.length?ts.map(thtml).join(''):empty('复习计划为空','从一个具体小任务开始。'));
 const fq=qs.filter(q=>filter==='all'||q.status===filter);set('#inboxList',fq.length?fq.map(q=>qhtml(q,true)).join(''):empty('这里没有问题','切换筛选条件查看其他记录。'));
 txt('#allCount',qs.length);txt('#pendingCount',pending);txt('#answeredCount',qs.length-pending);txt('#taskRate',rate+'%');document.querySelectorAll('#pendingBadge').forEach(e=>e.textContent=pending);document.querySelectorAll('#planRate').forEach(e=>e.textContent=rate+'%');
 const bar=document.querySelector('#planBar');if(bar)bar.style.width=rate+'%';
 set('#teacherFocus',pending?`<div class="item"><b>${pending} 个问题等待回复</b><div class="meta">建议优先处理提交时间较早的问题</div></div>`:empty('暂无紧急事项','所有问题均已处理。'));trend(qs)
}
document.querySelector('#askBtn')?.addEventListener('click',addQuestion);document.querySelector('#questionInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')addQuestion()});document.querySelectorAll('[data-fill]').forEach(x=>x.onclick=()=>{document.querySelector('#questionInput').value=x.dataset.fill;document.querySelector('#questionInput').focus()});document.querySelector('#addTask')?.addEventListener('click',addTask);document.querySelector('#taskInput')?.addEventListener('keydown',e=>{if(e.key==='Enter')addTask()});
document.querySelectorAll('[data-filter]').forEach(x=>x.onclick=()=>{filter=x.dataset.filter;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('on',b===x));render()});
document.querySelectorAll('[data-tool]').forEach(x=>x.onclick=()=>{activeTool=x.dataset.tool;document.querySelector('#toolTitle').textContent=activeTool+'工作区';document.querySelector('#toolInput').focus()});
window.chooseTool=x=>{activeTool=x;openView('tools');document.querySelector('#toolTitle').textContent=activeTool+'工作区'};
document.querySelector('#generate')?.addEventListener('click',()=>{const v=document.querySelector('#toolInput').value.trim();if(!v){toast('请先输入具体内容');return}const map={互动题:`主题：${v}\n\n1. 情境导入：用一个真实问题引出主题\n2. 独立思考：学生写下判断与理由\n3. 小组讨论：比较不同思路与分歧\n4. 教师点拨：回到核心概念，纠正常见误区\n5. 即时检验：用一道变式题确认理解`,教学行动:`需要解决的问题：${v}\n\n教学目标\n- 能用自己的语言解释核心概念\n- 能在新情境中选择合适方法\n\n教学行动\n1. 复盘高频错误\n2. 用可视化案例建立联系\n3. 安排基础—提升—迁移练习\n4. 收集课末反馈并调整任务`,学情摘要:`关注主题：${v}\n\n建议观察\n- 哪类问题反复出现\n- 哪些步骤最容易卡住\n- 哪些问题仍未解决\n- 学习任务完成情况\n\n后续行动\n- 补充真实作业或成绩数据\n- 区分共性困难与个别困难\n- 设定可验证的教学目标`,复习任务:`复习主题：${v}\n\n基础巩固：回顾定义、条件和典型例题\n能力提升：完成两道需要解释思路的变式题\n迁移应用：在新情境中选择方法并说明理由\n自我检查：写下仍不确定的一点并提交问题`};document.querySelector('#toolOutput').textContent=map[activeTool]||map['教学行动'];toast('结构已生成')});
document.querySelector('#copyOutput')?.addEventListener('click',async()=>{await navigator.clipboard.writeText(document.querySelector('#toolOutput').textContent);toast('已复制')});
document.querySelector('#exportData')?.addEventListener('click',()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.download='智学双擎_学习数据.json';a.click();toast('数据已导出')});
document.querySelector('#importFile')?.addEventListener('change',e=>{const f=e.target.files[0];if(!f)return;const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);if(!Array.isArray(x.questions)||!Array.isArray(x.tasks))throw 0;state=x;save();toast('导入成功')}catch{toast('文件格式不正确')}};r.readAsText(f)});
document.querySelector('#clearData')?.addEventListener('click',()=>{if(confirm('确定清空当前浏览器中的全部问题和任务吗？')){state={questions:[],tasks:[]};save();toast('数据已清空')}});
function particles(){const c=document.querySelector('#particles');if(!c)return;const x=c.getContext('2d');let w,h,p;function size(){w=c.width=innerWidth;h=c.height=innerHeight;p=Array.from({length:Math.min(75,Math.floor(w/20))},()=>({x:Math.random()*w,y:Math.random()*h,vx:(Math.random()-.5)*.2,vy:(Math.random()-.5)*.2,r:Math.random()*1.4+.3}))}function go(){x.clearRect(0,0,w,h);p.forEach(a=>{a.x+=a.vx;a.y+=a.vy;if(a.x<0||a.x>w)a.vx*=-1;if(a.y<0||a.y>h)a.vy*=-1;x.beginPath();x.arc(a.x,a.y,a.r,0,7);x.fillStyle='rgba(108,174,255,.48)';x.fill()});requestAnimationFrame(go)}size();go();addEventListener('resize',size)}particles();render();
