import { randomUUID } from "node:crypto";

export class LearningError extends Error { constructor(code,message,status=400){super(message);this.code=code;this.status=status;} }
const round=(value,digits=1)=>value===null||value===undefined?null:Math.round(Number(value)*10**digits)/10**digits;
const json=(value,fallback=[])=>{try{return JSON.parse(value)}catch{return fallback}};
const bool=value=>value===true||value===1;

export function createLearningService({ baseDb, runtimeStore, skills, audit=async()=>{} }) {
  const runtimeDb=runtimeStore.taskDatabase;
  function scope(context,studentNo){
    const match=/^teacher:(\d+):(\d+)$/.exec(String(context||""));if(!match)throw new LearningError("LEARNING_CONTEXT_INVALID","课程班级上下文不正确。");
    const row=baseDb.prepare(`SELECT s.id student_id,s.student_no,s.display_name,s.class_id,o.id offering_id,o.course_id,c.course_code,c.course_name,cl.class_name
      FROM students s JOIN classes cl ON cl.id=s.class_id JOIN enrollments e ON e.student_id=s.id AND e.status<>'退选'
      JOIN course_offerings o ON o.id=e.offering_id JOIN courses c ON c.id=o.course_id JOIN offering_classes oc ON oc.offering_id=o.id AND oc.class_id=s.class_id
      WHERE o.id=? AND s.class_id=? AND s.student_no=?`).get(Number(match[1]),Number(match[2]),String(studentNo||""));
    if(!row)throw new LearningError("AUTH_STUDENT_SCOPE_FORBIDDEN","该学生不在当前教师的课程班级范围内。",403);return row;
  }
  function preferences(studentId,offeringId){const row=runtimeDb.prepare("SELECT * FROM runtime_student_sharing_preferences WHERE student_id=? AND offering_id=?").get(studentId,offeringId);return row?{behaviorDetails:bool(row.behavior_details),answerText:bool(row.answer_text),qaContent:bool(row.qa_content),goalsPreferences:bool(row.goals_preferences),version:row.version,updatedAt:row.updated_at}:{behaviorDetails:false,answerText:false,qaContent:false,goalsPreferences:false,version:0,updatedAt:null};}
  function knowledge(studentId,courseId){return baseDb.prepare(`SELECT kp.id,kp.name,ROUND(ms.mastery*100,1) value,ms.trend,ms.evidence_count evidenceCount,ROUND(ms.confidence*100,1) confidence
      FROM mastery_snapshots ms JOIN knowledge_points kp ON kp.id=ms.knowledge_point_id
      WHERE ms.student_id=? AND kp.course_id=? AND ms.measured_at=(SELECT MAX(x.measured_at) FROM mastery_snapshots x WHERE x.student_id=ms.student_id AND x.knowledge_point_id=ms.knowledge_point_id)
      ORDER BY ms.mastery,kp.name`).all(studentId,courseId);}
  function metrics(studentId,offeringId,courseId){
    const enrollment=baseDb.prepare("SELECT final_score FROM enrollments WHERE student_id=? AND offering_id=?").get(studentId,offeringId);
    const attendance=baseDb.prepare("SELECT COUNT(*) total,SUM(CASE WHEN status IN ('出勤','迟到') THEN 1 ELSE 0 END) present FROM attendance_records WHERE student_id=? AND offering_id=?").get(studentId,offeringId);
    const assignments=baseDb.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN ta.status='已完成' THEN 1 ELSE 0 END) done,SUM(CASE WHEN ta.status='已逾期' THEN 1 ELSE 0 END) overdue FROM task_assignments ta JOIN learning_tasks lt ON lt.id=ta.task_id WHERE ta.student_id=? AND lt.offering_id=?`).get(studentId,offeringId);
    const wrong=baseDb.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN wb.review_status='已掌握' THEN 1 ELSE 0 END) reviewed FROM wrong_book_entries wb JOIN knowledge_points kp ON kp.id=wb.knowledge_point_id WHERE wb.student_id=? AND kp.course_id=?`).get(studentId,courseId);
    const risk=baseDb.prepare("SELECT risk_level,risk_type,risk_score,evidence_json,created_at FROM risk_alerts WHERE student_id=? AND offering_id=? AND status<>'已关闭' ORDER BY risk_score DESC LIMIT 1").get(studentId,offeringId);
    const activity=baseDb.prepare(`SELECT MAX(le.occurred_at) last_active FROM learning_events le JOIN learning_resources lr ON lr.id=le.resource_id WHERE le.student_id=? AND lr.course_id=?`).get(studentId,courseId);
    return{score:round(enrollment?.final_score),attendanceRate:attendance?.total?round(attendance.present*100/attendance.total):null,taskCompletionRate:assignments?.total?round(assignments.done*100/assignments.total):null,taskTotal:Number(assignments?.total||0),taskDone:Number(assignments?.done||0),overdueCount:Number(assignments?.overdue||0),wrongCount:Number(wrong?.total||0),reviewedWrongCount:Number(wrong?.reviewed||0),risk:risk?{level:risk.risk_level,type:risk.risk_type,score:round(risk.risk_score*100),evidence:json(risk.evidence_json),createdAt:risk.created_at}:null,lastActiveAt:activity?.last_active||null};
  }
  function profileFor(row){const points=knowledge(row.student_id,row.course_id),m=metrics(row.student_id,row.offering_id,row.course_id);const mastery=points.length?round(points.reduce((s,x)=>s+x.value,0)/points.length):null;const result=skills.studentProfile.analyze({scope:`student:${row.student_no}:offering:${row.offering_id}`,knowledge_points:points,attendance_rate:m.attendanceRate,task_completion_rate:m.taskCompletionRate,wrong_count:m.wrongCount,trend:points.filter(x=>x.trend==='上升').length>=points.filter(x=>x.trend==='下降').length?'总体稳定或上升':'近期有下降'});return{points,metrics:m,mastery,analysis:result};}
  function listStudents(context){const match=/^teacher:(\d+):(\d+)$/.exec(String(context||""));if(!match)throw new LearningError("LEARNING_CONTEXT_INVALID","课程班级上下文不正确。");const rows=baseDb.prepare(`SELECT s.id student_id,s.student_no,s.display_name,s.class_id,o.id offering_id,o.course_id,c.course_code,c.course_name,cl.class_name FROM students s JOIN classes cl ON cl.id=s.class_id JOIN enrollments e ON e.student_id=s.id AND e.status<>'退选' JOIN course_offerings o ON o.id=e.offering_id JOIN courses c ON c.id=o.course_id WHERE o.id=? AND s.class_id=? ORDER BY s.student_no`).all(Number(match[1]),Number(match[2]));return rows.map(row=>{const p=profileFor(row);return{studentNo:row.student_no,displayName:row.display_name,score:p.metrics.score,mastery:p.mastery,attendanceRate:p.metrics.attendanceRate,taskCompletionRate:p.metrics.taskCompletionRate,weakPoints:p.analysis.profile.weaknesses.map(x=>x.name),risk:p.metrics.risk,lastActiveAt:p.metrics.lastActiveAt,evidenceCount:p.analysis.evidence.reduce((s,x)=>s+Number(x.count||1),0)}});}
  async function observation(context,studentNo,teacherId){const row=scope(context,studentNo),p=profileFor(row),prefs=preferences(row.student_id,row.offering_id);const shared={required:{score:p.metrics.score,mastery:p.mastery,knowledge:p.points,tasks:{total:p.metrics.taskTotal,done:p.metrics.taskDone,completionRate:p.metrics.taskCompletionRate,overdue:p.metrics.overdueCount},wrongBook:{total:p.metrics.wrongCount,reviewed:p.metrics.reviewedWrongCount},attendanceRate:p.metrics.attendanceRate,risk:p.metrics.risk},optional:{behaviorDetails:prefs.behaviorDetails?{lastActiveAt:p.metrics.lastActiveAt}:null,answerText:prefs.answerText?baseDb.prepare(`SELECT ai.prompt,iscore.answer_text,iscore.error_type FROM item_scores iscore JOIN assessment_items ai ON ai.id=iscore.item_id JOIN submissions sub ON sub.id=iscore.submission_id JOIN assessments a ON a.id=sub.assessment_id WHERE sub.student_id=? AND a.offering_id=? ORDER BY sub.submitted_at DESC LIMIT 10`).all(row.student_id,row.offering_id):null,qaContent:prefs.qaContent?runtimeStore.getStudentQa(`student:${row.student_no}`,row.offering_id,20).map(x=>({question:x.question,status:x.status,answer:x.assistantAnswer,createdAt:x.createdAt})):null,goalsPreferences:prefs.goalsPreferences?{profileTags:json(baseDb.prepare("SELECT profile_tags FROM students WHERE id=?").get(row.student_id)?.profile_tags)}:null}};runtimeDb.prepare("INSERT INTO runtime_observation_audits(id,teacher_id,student_id,offering_id,class_id,fields_json,created_at) VALUES(?,?,?,?,?,?,?)").run(`obs_${randomUUID()}`,teacherId,row.student_id,row.offering_id,row.class_id,JSON.stringify({required:true,preferences:prefs}),new Date().toISOString());await audit({actorRole:'teacher',action:'observe_student',objectType:'student_learning_profile',objectRef:row.student_no,result:'success',context});return{mode:'teacher_observation_readonly',student:{studentNo:row.student_no,displayName:row.display_name,className:row.class_name},course:{offeringId:row.offering_id,courseCode:row.course_code,courseName:row.course_name},sharing:prefs,profile:p.analysis,shared,permissions:{canWriteStudentData:false,canDraftPlan:true}};}
  function getStudentPreferences(studentId,offeringId){return preferences(studentId,offeringId);}
  function updateStudentPreferences(studentId,offeringId,input){const current=preferences(studentId,offeringId),now=new Date().toISOString(),next={behaviorDetails:bool(input.behaviorDetails),answerText:bool(input.answerText),qaContent:bool(input.qaContent),goalsPreferences:bool(input.goalsPreferences)};runtimeDb.prepare(`INSERT INTO runtime_student_sharing_preferences(student_id,offering_id,behavior_details,answer_text,qa_content,goals_preferences,version,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(student_id,offering_id) DO UPDATE SET behavior_details=excluded.behavior_details,answer_text=excluded.answer_text,qa_content=excluded.qa_content,goals_preferences=excluded.goals_preferences,version=runtime_student_sharing_preferences.version+1,updated_at=excluded.updated_at`).run(studentId,offeringId,next.behaviorDetails?1:0,next.answerText?1:0,next.qaContent?1:0,next.goalsPreferences?1:0,current.version+1,now);return preferences(studentId,offeringId);}
  function mapPlan(row){return row?{planId:row.id,studentNo:row.student_no,offeringId:row.offering_id,classId:row.class_id,versionNo:row.version_no,status:row.status,goal:row.goal,route:row.route,dueAt:row.due_at,tasks:json(row.tasks_json),whyRecommended:json(row.basis_json),skillVersion:row.skill_version,createdAt:row.created_at,updatedAt:row.updated_at,publishedAt:row.published_at}:null;}
  function createPlanDraft(context,studentNo){const row=scope(context,studentNo),p=profileFor(row),next=runtimeDb.prepare("SELECT COALESCE(MAX(version_no),0)+1 n FROM runtime_personal_plans WHERE student_id=? AND offering_id=?").get(row.student_id,row.offering_id).n,generated=skills.learningPlanner.plan({scope:`student:${row.student_no}:offering:${row.offering_id}`,profile:p.analysis.profile,evidence:p.analysis.evidence}),now=new Date().toISOString(),id=`pp_${randomUUID()}`;runtimeDb.prepare(`INSERT INTO runtime_personal_plans(id,student_id,student_no,offering_id,class_id,teacher_context,version_no,status,goal,route,due_at,tasks_json,basis_json,skill_version,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,row.student_id,row.student_no,row.offering_id,row.class_id,context,next,'draft',generated.goal,generated.route,generated.due_at,JSON.stringify(generated.tasks),JSON.stringify(generated.why_recommended),generated.skill_version,now,now);return mapPlan(runtimeDb.prepare("SELECT * FROM runtime_personal_plans WHERE id=?").get(id));}
  function updatePlan(context,planId,input){const row=runtimeDb.prepare("SELECT * FROM runtime_personal_plans WHERE id=? AND teacher_context=?").get(planId,context);if(!row)throw new LearningError('PLAN_FORBIDDEN','无权访问该计划。',403);if(row.status!=='draft')throw new LearningError('PLAN_NOT_EDITABLE','只有草案可以编辑。',409);const goal=String(input.goal||row.goal).trim().slice(0,500),route=String(input.route||row.route).trim().slice(0,80),due=new Date(input.dueAt||row.due_at);if(!goal||Number.isNaN(due.getTime()))throw new LearningError('PLAN_INVALID','计划目标或截止时间不正确。');const tasks=Array.isArray(input.tasks)?input.tasks.map(x=>({title:String(x.title||'').trim().slice(0,120),type:String(x.type||'学习任务').slice(0,40),knowledge_point:String(x.knowledge_point||'').slice(0,120),difficulty:String(x.difficulty||'标准').slice(0,20),duration_minutes:Math.max(5,Math.min(240,Number(x.duration_minutes)||20)),resource:String(x.resource||'').slice(0,300),reason:String(x.reason||'').slice(0,300)})).filter(x=>x.title):json(row.tasks_json);if(!tasks.length)throw new LearningError('PLAN_TASKS_EMPTY','计划至少需要一个任务。');runtimeDb.prepare("UPDATE runtime_personal_plans SET goal=?,route=?,due_at=?,tasks_json=?,updated_at=? WHERE id=?").run(goal,route,due.toISOString(),JSON.stringify(tasks),new Date().toISOString(),planId);return mapPlan(runtimeDb.prepare("SELECT * FROM runtime_personal_plans WHERE id=?").get(planId));}
  function publishPlan(context,planId){const row=runtimeDb.prepare("SELECT * FROM runtime_personal_plans WHERE id=? AND teacher_context=?").get(planId,context);if(!row)throw new LearningError('PLAN_FORBIDDEN','无权访问该计划。',403);if(row.status==='published')return mapPlan(row);if(row.status!=='draft')throw new LearningError('PLAN_NOT_PUBLISHABLE','当前计划不能发布。',409);const now=new Date().toISOString();runtimeDb.exec('BEGIN IMMEDIATE');try{runtimeDb.prepare("UPDATE runtime_personal_plans SET status='superseded',updated_at=? WHERE student_id=? AND offering_id=? AND status='published'").run(now,row.student_id,row.offering_id);runtimeDb.prepare("UPDATE runtime_personal_plans SET status='published',published_at=?,updated_at=? WHERE id=? AND status='draft'").run(now,now,planId);runtimeDb.exec('COMMIT')}catch(error){runtimeDb.exec('ROLLBACK');throw error}return mapPlan(runtimeDb.prepare("SELECT * FROM runtime_personal_plans WHERE id=?").get(planId));}
  function studentPlans(studentId,offeringId){return runtimeDb.prepare("SELECT * FROM runtime_personal_plans WHERE student_id=? AND offering_id=? AND status='published' ORDER BY published_at DESC LIMIT 1").all(studentId,offeringId).map(mapPlan);}
  return{listStudents,observation,getStudentPreferences,updateStudentPreferences,createPlanDraft,updatePlan,publishPlan,studentPlans,scope};
}
